options:
  log_level:
    description: |
      Configures the log level.

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  base_dn:
    description: The base DN
    default: "dc=glauth,dc=com"
    type: string
  hostname:
    description: |
      The hostname of the LDAP server.

      The hostname should NOT contain the LDAP scheme (e.g. ldap://) and port.
    default: "ldap.glauth.com"
    type: string
  starttls_enabled:
    description: |
      Enable the StartTLS support or not. DO NOT TURN IT OFF IN PRODUCTION.
    default: true
    type: boolean
