# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "glauth-k8s-operator"
version = "0.1.0"
description = "A Charmed Operator for running GLAuth on Kubnernetes"
requires-python = ">=3.8"
readme = "README.md"
license = {file = "LICENSE"}

dynamic = ["version"]

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"

# Formatting tools configuration
[tool.black]
line-length = 80
target-version = ["py38"]

[tool.isort]
line_length = 80
profile = "black"

# Linting tools configuration
[tool.flake8]
max-line-length = 80
max-doc-length = 80
max-complexity = 10
exclude = [".git", "__pycache__", ".tox", "build", "dist", "*.egg_info", "venv"]
select = ["E", "W", "F", "C", "N", "R", "D", "H"]
# https://www.flake8rules.com/
# https://www.pydocstyle.org/en/latest/error_codes.html#error-codes
# Ignore W503, E501 because using black creates errors with this
# Ignore D107 Missing docstring in __init__
ignore = ["W503", "E501", "D100", "D101", "D102", "D103", "D107"]
# D100, D101, D102, D103: Ignore missing docstrings in tests
per-file-ignores = ["tests/*:D100,D101,D102,D103,D104"]
docstring-convention = "google"
# Check for properly formatted copyright header in each file
copyright-check = "True"
copyright-author = "Canonical Ltd."
copyright-regexp = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+%(author)s"

[tool.mypy]
pretty = true
mypy_path = "./src:./lib/:./tests"
# Exclude non-glauth libraries
exclude = 'lib/charms/((?!glauth_k8s/).)'
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_configs = true
show_traceback = true
show_error_codes = true
namespace_packages = true
explicit_package_bases = true
check_untyped_defs = true
allow_redefinition = true
disallow_incomplete_defs = true
disallow_untyped_defs = true

# Ignore libraries that do not have type hint nor stubs
[[tool.mypy.overrides]]
module = ["ops.*", "pytest.*", "pytest_operator.*", "urllib3.*", "jinja2.*", "lightkube.*", "pytest_mock.*"]
ignore_missing_imports = true
